:setvar SQLCMDMAXVARTYPEWIDTH 20
CREATE TABLE $(TABLE) (id INT NOT NULL PRIMARY KEY, name NVARCHAR(20));
GO
INSERT INTO $(TABLE) VALUES (1, 'one'), (2, 'two'), (3, NULL);
GO
SELECT id, name FROM $(TABLE) ORDER BY id;
GO
SELECT COUNT(*) AS n FROM $(TABLE) WHERE name IS NOT NULL;
GO
BEGIN TRANSACTION;
UPDATE $(TABLE) SET name = 'uno' WHERE id = 1;
ROLLBACK;
GO
SELECT name FROM $(TABLE) WHERE id = 1;
GO
